// 1. Ready translated locale messages
// The structure of the locale message is the hierarchical object structure with each locale as the top property
import VueI18n from 'vue-i18n';
import Vue from 'vue';

Vue.use(VueI18n)

const messages = {
  en: {
    email: "Email",
    accountType: "Account Type",
    country: "Country",
    security: "2FA",
    name: "Your Name",
    setPwd: "Set Password",
    createQQPay: 'Create QQPay Account',
    signupProcess: `let's start the sign up process with your personal/professional Email ID`,
    emailID: 'Email ID',
    next: 'Next',
    signupAgree: 'By Signing up your agree to our Terms&Conditions and Privacy Policy',
    alreadyAccount: 'Already have an Account? Log in',
    openaccountType: 'what kind of account would you like to open?',
    accountSelection: 'Account type selection',
    personal: 'Personal',
    business: 'Business',
    personalQuotes: 'Send,spend and receive around the world for less',
    businessQuotes: 'Do business or freelance work internationally',
    backLabel: 'Back',
    nextLabel: 'Next',
    countryResiding: 'Select the Country you are currently residing',
    sourceCountry: 'This will be the source country for all of your transactions',
    verifyPhone: 'Verify your phone number with a OTP',
    helpups: 'it helps us keep your account secure',
    phoneNumber: ' Phone Number',
    getOTP: 'Get OTP',
    goodName: 'Let us Know your Good Name',
    finisProcess: 'you are almost there to finish the sign up process!',
    fName: 'First Name',
    lName: 'Last Name',
    setAccountPass: 'Set Your Account password',
    setStrongPassword: 'Set a strong password and finish the sign up process!',
    currentPass: 'Password',
    confirmPass: 'Re-Enter Password',
    passwordStrength: 'Min. 8 characters, one upper & lowercase,one number, one special character.',
    createAccount: 'Create Account',
    loginScreen: {
      paymentAccrossGlb: 'Payment Across The Globe Got Easier',
      paymentSubheader: 'We remove complexities and introducing you to fast,cost-effective international payments with greater transparency',
      signin: 'Sign In',
      someoneExample: '',
      password: '',
      forgotPassword: 'Forgot Password',
      singnupOption: 'Sign-up options',
    },
    beneficiary: {
      addBeneficiary: 'Add Beneficiary',
      accountType: 'Account Type',
      basicDetails: 'Basic Details',
      address: 'Address',
      bankDetails: 'Bank Details',
      kindOfBenficiary: 'What kind of beneficiary would you like to add',
      individual: 'Individual',
      business: 'Business',
      individualSubHeader: 'send,spend and receive around the world for less',
      businessSubHeader: 'Do business or freelance work internationally',
      next: 'Next',
      letusSomeBasic: 'Let us get some basic details of the beneficiary',
      fullName: 'Full name of the beneficiary',
      country: 'Beneficiary Country',
      relationship: 'Relationship',
      phoneNumber: 'Phone Number',
      emailAddress: 'Email Address',
      optional: 'optional',
      enterAddressBeneficiary: 'Please enter address of the beneficiary',
      state: 'State',
      city: 'City',
      bankAccuntDetails: 'Please enter bank account details of the beneficiary',
      bankAccountNumber: 'Bank Account Number',
      renterBankAccount: 'Re-Enter Account Number',
      swiftCode: 'SWIFT/BIC Code',
      createBeneficiary: 'Create Beneficiary',
    },
    forgetPassowrd: {
      forgotPassword: 'Forgot Password',
      enterEmailId: '',
      getOtp: 'Get OTP',
    }
  },
  ch: {
    email: "邮箱" ,
    accountType: "账户类型" ,
    country: "国家",
    security: "2FA",
    name: "您的姓名",
    setPwd: "设置密码",
    createQQPay: '创建QQPay账户',
    signupProcess: '开始使用您的个人/专业邮箱ID注册',
    emailID: '邮箱ID',
    next: '下一步',
    signupAgree: '注册即表示，您同意我们的条款和条件及隐私政策',
    alreadyAccount: '已有账户？登录',
    openaccountType: '您想开什么类型的账户？',
    accountSelection: '账户类型选择',
    personal: '个人账户',
    business: '公司账户',
    personalQuotes: '花更少的钱在世界各地转账、消费和收款',
    businessQuotes: '在国际上开展公司业务或者自由职业',
    backLabel: '返回',
    nextLabel: '下一步',
    countryResiding: '请选择您目前居住的国家',
    sourceCountry: '这将是您所有交易的来源国家',
    verifyPhone: '通过验证码验证您的电话号码',
    helpups: '它能帮助我们确保您的账户安全',
    phoneNumber: '电话号码',
    getOTP: '收取验证码',
    goodName: '让我们知道您的名字',
    finisProcess: '即将完成注册！',
    fName: '名字',
    lName: '姓氏',
    setAccountPass: '设置您的账户密码',
    setStrongPassword: '设置一个强密码并完成注册！',
    currentPass: '密码',
    confirmPass: '重新输入密码',
    passwordStrength: '最少8个字符，并含有一个大写字母和小写字母、一个数字，以及一个特殊字符。',
    createAccount: '创建账户',
    loginScreen: {
      paymentAccrossGlb: '全球支付更加便捷',
      paymentSubheader: '我们消除了复杂的操作，为您带来快速、低费率、高透明度的国际支付体验',
      signin: '登录',
      someoneExample: '',
      password: '',
      forgotPassword: '忘记密码',
      singnupOption: '注册选项',
    },
    beneficiary: {
      addBeneficiary: '添加收款人',
      accountType: '账户类型',
      basicDetails: '基本的细节',
      address: '地址',
      bankDetails: '银行资料',
      kindOfBenficiary: '您想要增加什么样的收款人',
      individual: '个人',
      business: '公司账户',
      individualSubHeader: '花更少的钱在世界各地转账、消费和收款',
      businessSubHeader: '在国际上开展公司业务或者自由职业',
      next: '下一步',
      letusSomeBasic: '让我们来了解一下收款人的基本信息',
      fullName: '收款人全名',
      country: '收款人国家',
      relationship: '关系',
      phoneNumber: '电话号码',
      emailAddress: '电子邮件地址',
      optional: '可选',
      enterAddressBeneficiary: '请输入收款人地址',
      state: '邦',
      city: '城市',
      bankAccuntDetails: '请输入收款人的银行账户资料',
      bankAccountNumber: '银行账户号码',
      renterBankAccount: '重新输入账号',
      swiftCode: 'SWIFT/BIC代码',
      createBeneficiary: '创建收款人',
    },
    forgetPassowrd: {
      forgotPassword: '忘记密码',
      enterEmailId: '',
      getOtp: '收取验证码',
    }
  }
}
  
// 2. Create i18n instance with options
export const i18n = new VueI18n({
  locale: 'ch',
  messages,
});